version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: npm run start:dev
  bd:
    image: postgres:15
    container_name: nestjs_bd
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs
volumes:
  pgdata:
