services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: npm run start:dev